### PR TITLE
add 2 useful redshift functions

### PR DESCRIPTION
**Pull request by niklasvm**
(1) list all available tables on redshift database
(2) Show table information for a given input table

### CODE REVIEW

**Comment by sicarul** [comment]
Hey sorry for the delay, you rock, i'll merge this asap

**Comment by sicarul** [comment]
@niklasvm about `rs_table_def`, it forces you to use format `public.mytable` or `whateverschema.mytable`, how about we make table and  schema two parameters, with the default value for schema = 'public'? Because a lot of people might only be using one schema since that's the default and might confuse people to require them to put it? What do you think?

**Comment by niklasvm** [comment]
That's a good idea. I'll make the change.

**Comment by niklasvm** [comment]
I've adjusted it. Give it a test drive

**Review by sicarul — APPROVED** [review]
Jeez, forgot to merge this

**Pull request merged**
