### PR TITLE
multibyte character

### PR DESCRIPTION
**Pull request by tsydorenko**
I had an issue while importing data which contained text with multibyte characters into Redshift. 
```
text<- "Γεια πώς είσαι?"
n_chars<-nchar(text)
n_bytes<- nchar(text,type="bytes")
df<- cbind.data.frame(text,n_chars,n_bytes)
df
 text n_chars n_bytes
1 Γεια πώς είσαι?      15      27

rs_create_table(
  df,
  dbcon=con_db, 
  table_name='redshift_data_table', 
  region=my_region,bucket=my_bucket,
  access_key=my_acces_key,
  secret_key=my_secret_key
)
```

With the current package version I received `Failed to fetch row: ERROR:  Load into table 'pdojeifamlzhgsyu' failed.  Check 'stl_load_errors' system table for details.` Then I tried to change the schema definition of the VARCHAR columns to number of bytes instead of number of the characters and everything worked perfectly. I hope this can save some time for other users who importing multibyte strings to Redshift :)

### CODE REVIEW

**Comment by JakeRuss** [comment]
If you file this PR over at https://github.com/RedOakStrategic/redshiftTools I will merge it into the development version I am working on there

**Comment by tsydorenko** [comment]
@JakeRuss sure! already on it

**Comment by JakeRuss** [comment]
@tsydorenko Please delete this PR and file a new one at the other repository, sicarul is no longer working on this project.

**Comment by sicarul** [comment]
Thanks for keeping the project alive @JakeRuss ! 😄

**Pull request closed without merging**
