### PR TITLE
Adding session token functionality

### PR DESCRIPTION
**Pull request by rtjohn**
On EC2s with an IAM role, AWS issues credentials to the device.  Those credentials include a session token that cloudyR know to look for.  This PR includes minor changes to let redshiftTools pass session tokens to the functions in cloudyR that need them.

### CODE REVIEW

**Comment by sicarul** [comment]
Sorry for the delay @rtjohn , i'll try to review it this weekend

**Comment by sicarul** [comment]
Is there any chance you can squash your commits? https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/
Not necessarily into one, maybe into two or three is fine.

**Comment by sicarul** [comment]
Thanks for the contribution @rtjohn ! Merged!

**Comment by rtjohn** [comment]
Ah.  Very sorry I didn't get around to squashing my comments.  I've been focused on contributing to our work repos.  Thanks for merging.  I hope to contribute more in the future.

**Pull request merged**
